apiVersion: v1
kind: Service
metadata:
  name: spring-test-service
spec:
  selector:
    app: spring-test-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-aqa-uade
spec:
  selector:
    matchLabels:
      app: weather-api-aqa-uade
  replicas: 2
  template:
    metadata:
      labels:
        app: weather-api-aqa-uade
    spec:
      containers:
        - name: weather-api-aqa-uade
          image: weather-api-aqa-uade
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080